// src/components/curriculum-header.tsx
import { DynamicSpan } from '@components/dynamic-span'
import { me } from '@utils/me'

export const CurriculumHeader = () => {
	return (
		<>
			<p aria-hidden className="h-[2px] bg-[url('/pattern.svg')]" />
			<div className='grid gap-3 text-center md:grid-cols-2 md:grid-rows-3 p-4 rounded-lg'>
				{me('en').info.map(({ Icon, text, href }) => (
					<DynamicSpan key={text} href={href}>
						<Icon weight='fill' strokeWidth={1.5} />
						<span>{text}</span>
					</DynamicSpan>
				))}
			</div>
			<p aria-hidden className="h-[2px] bg-[url('/pattern.svg')]" />
		</>
	)
}

// app/components/CurriculumHeader.vue
<script lang="ts" setup>
import { me } from '@@/utils'
</script>

<template>
	<p aria-hidden class="h-[2px] bg-[url('/pattern.svg')]" />
	<div
		class="grid gap-3 text-center md:grid-cols-2 md:grid-rows-3 p-4 rounded-lg">
		<DynamicSpan
			v-for="({ Icon, text, href }, id) in me('en').info"
			:href="href"
			:key="id">
			<component :is="Icon" weight="fill" :stroke-width="1.5" />
			<span>{{ text }}</span>
		</DynamicSpan>
	</div>
	<p aria-hidden class="h-[2px] bg-[url('/pattern.svg')]" />
</template>
