// src/components/dynamic-span.tsx
type Props = {
	href?: string
	children: React.ReactNode
}

export const DynamicSpan = ({ href, children }: Props) => {
	return (
		<>
			{href ? (
				<a
					href={href}
					rel='noreferrer'
					target='_blank'
					className='flex items-center gap-2 decoration-primary-1 hover:underline '>
					{children}
				</a>
			) : (
				<span className='flex items-center gap-2 '>{children}</span>
			)}
		</>
	)
}

// app/components/DynamicSpan.vue
<script lang="ts" setup>
type Props = {
	href?: string
}

const { href } = defineProps<Props>()
</script>

<template>
	<a
		v-if="href"
		:href="href"
		rel="noreferrer"
		target="_blank"
		class="flex items-center gap-2 decoration-primary-1 hover:underline">
		<slot />
	</a>
	<span v-else class="flex items-center gap-2"><slot /></span>
</template>
