// src/components/Navbar/Navbar.tsx
import { GitHubLogoIcon } from "@radix-ui/react-icons"
import clsx from "clsx"
import Link from "next/link"
import { useRouter } from "next/router"

const links: { name: string; pathname: string }[] = [
  /*   {
    name: "snippets",
    pathname: "/snippets"
  }, */
  {
    name: "contact",
    pathname: "/contact"
  },
  {
    name: "curriculum",
    pathname: "/curriculum"
  }
]

export const Navbar = () => {
  const { pathname } = useRouter()
  return (
    <nav className="fixed top-0 left-0 z-50 flex h-16 w-full items-center justify-between bg-background/50 px-20 shadow-[0_1px_4px_0_#151517] backdrop-blur-[3px]">
      <div className="flex items-center gap-4">
        <Link href="/" className="flex items-center justify-center gap-1">
          {pathname === "/" ? <BreathingLogo /> : <Logo />}
        </Link>
        {links.map(link => (
          <Link
            key={link.name}
            href={link.pathname}
            className={clsx("hidden text-xl hover:text-primary sm:inline", {
              "text-primary": pathname === link.pathname
            })}>
            {link.name}
          </Link>
        ))}
      </div>
      <div className="flex items-center gap-4 sm:hidden">
        {links.map(link => (
          <Link
            key={link.name}
            href={link.pathname}
            className={clsx("text-lg hover:text-primary", {
              "text-primary": pathname === link.pathname
            })}>
            {link.name}
          </Link>
        ))}
      </div>
      <div className="hidden items-center justify-center gap-5 sm:flex">
        <a
          className="hover:text-primary"
          href="https://github.com/isneru"
          target="_blank"
          rel="noreferrer">
          <GitHubLogoIcon role="img" width={20} height={20} />
        </a>
      </div>
    </nav>
  )
}

const BreathingLogo = () => {
  return (
    <>
      <div className="flex h-8 w-8 animate-background items-center justify-center rounded-xl bg-primary sm:h-6 sm:w-6 sm:rounded-lg">
        <div className="h-3.5 w-0.5 rotate-[30deg] rounded-full bg-background sm:h-3 sm:w-0.5" />
      </div>
      <div className="hidden text-xl font-bold sm:block">
        <span className="animate-color">diogo</span>
      </div>
    </>
  )
}

const Logo = () => {
  return (
    <>
      <div className="flex h-8 w-8 items-center justify-center rounded-xl border-2 border-text bg-background sm:h-6 sm:w-6 sm:rounded-lg">
        <div className="h-3.5 w-0.5 rotate-[30deg] rounded-full bg-text sm:h-3 sm:w-0.5"></div>
      </div>
      <div className="hidden text-xl font-bold sm:block">
        <span>diogo</span>
      </div>
    </>
  )
}

// src/components/navbar.tsx
import { A, useLocation } from '@solidjs/router'
import clsx from 'clsx'
import { Motion, Presence } from 'solid-motionone'
import { Component, createMemo, Show } from 'solid-js'

export const Navbar: Component = () => {
	const location = useLocation()
	const pathname = createMemo(() => location.pathname)

	return (
		<nav class='fixed mx-auto top-6 left-0 right-0 z-50 flex h-16 items-center justify-between shadow-[0_1px_4px_0_#D77A6120] select-none print:hidden w-[90vw] rounded-xl border border-primary-1/10 bg-primary-3/40 px-6 py-3 backdrop-blur-[8px] transition-all duration-300 ease-in-out md:w-[calc(100%-1rem)] md:px-8 lg:w-[calc(100%-4rem)] xl:max-w-7xl'>
			<Motion.div
				initial={{ opacity: 0, x: 100 }}
				animate={{ opacity: 1, x: 0 }}>
				<A
					href='/'
					class={clsx(
						'flex items-center justify-center gap-2 text-xl font-semibold hover:text-primary-1 relative',
						{
							'text-primary-1': pathname() === '/'
						}
					)}>
					<Presence>
						<Show when={pathname() === '/'}>
							<Motion.span
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								class='bg-primary-2 absolute -left-4 top-2 size-2 rounded-full'
							/>
						</Show>
					</Presence>
					diogo
				</A>
			</Motion.div>
			<Motion.div
				initial={{ opacity: 0, x: -100 }}
				animate={{ opacity: 1, x: 0 }}
				class='flex items-center gap-4'>
				<A
					href={`/curriculum/${pathname().endsWith('en') ? 'pt' : 'en'}`}
					class={clsx('text-lg hover:text-primary-1 font-semibold relative', {
						'text-primary-1': pathname().includes('/curriculum')
					})}>
					<Presence>
						<Show when={pathname().includes('/curriculum')}>
							<Motion.span
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								class='bg-primary-2 absolute -left-4 top-2 size-2 rounded-full'
							/>
						</Show>
					</Presence>
					{`curriculum (${pathname().includes('en') ? 'pt' : 'en'})`}
				</A>
			</Motion.div>
		</nav>
	)
}
